name: Deploy to VM

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Upload project to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "./code"
          target: "/home/${{ secrets.SSH_USER }}/deploy-temp"
          overwrite: true

      - name: Deploy on VM
        uses: appleboy/ssh-action@v1.0.3
        env:
          DB_URL: "http://localhost" # Remplacer par votre URL de base de données
          PORT: "3000"
        with:
          envs: DB_URL,PORT
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |

            cd /home/${{ secrets.SSH_USER }}/deploy-temp/code
            sudo docker compose up -d --build

            cd /home/${{ secrets.SSH_USER }}/deploy-temp/code/backend
            npm install --omit=dev
            # Les variables DB_URL et PORT sont passées via 'envs'
            npm start

            cd /home/${{ secrets.SSH_USER }}/deploy-temp/code/frontend
            npm install
            npm run build

            sudo rm -rf /var/www/html/*
            sudo cp -r dist/* /var/www/html/
