name: deploy todo app

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Upload to VM temp
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "./code"
          target: "/home/${{ secrets.SSH_USER }}/deploy-temp"
          overwrite: true

      - name: Debug SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            ls -la /home/${{ secrets.SSH_USER }}

            ls -la /home/${{ secrets.SSH_USER }}/deploy-temp || echo "deploy-temp introuvable"

            find /home/${{ secrets.SSH_USER }}/deploy-temp -maxdepth 2
